// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  investigationId: __t.string().name("investigation_id"),
  owner: __t.identity(),
  capability: __t.string(),
  provider: __t.string(),
  status: __t.string(),
  detail: __t.string(),
  metric: __t.string(),
  durationMs: __t.u32().name("duration_ms"),
  externalRef: __t.string().name("external_ref"),
  startedAt: __t.string().name("started_at"),
  completedAt: __t.string().name("completed_at"),
});
