// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  owner: __t.identity(),
  subjectName: __t.string().name("subject_name"),
  context: __t.string(),
  status: __t.string(),
  consistencyScore: __t.i32().name("consistency_score"),
  stageIndex: __t.u32().name("stage_index"),
  progressPercent: __t.u32().name("progress_percent"),
  recordJson: __t.string().name("record_json"),
  createdAt: __t.string().name("created_at"),
  updatedAt: __t.string().name("updated_at"),
});
