// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Claims = __t.object("Claims", {
  id: __t.string(),
  investigationId: __t.string(),
  recordJson: __t.string(),
});
export type Claims = __Infer<typeof Claims>;

export const Embeddings = __t.object("Embeddings", {
  id: __t.string(),
  investigationId: __t.string(),
  recordJson: __t.string(),
});
export type Embeddings = __Infer<typeof Embeddings>;

export const IntegrationRuns = __t.object("IntegrationRuns", {
  id: __t.string(),
  investigationId: __t.string(),
  owner: __t.identity(),
  capability: __t.string(),
  provider: __t.string(),
  status: __t.string(),
  detail: __t.string(),
  metric: __t.string(),
  durationMs: __t.u32(),
  externalRef: __t.string(),
  startedAt: __t.string(),
  completedAt: __t.string(),
});
export type IntegrationRuns = __Infer<typeof IntegrationRuns>;

export const Investigations = __t.object("Investigations", {
  id: __t.string(),
  owner: __t.identity(),
  subjectName: __t.string(),
  context: __t.string(),
  status: __t.string(),
  consistencyScore: __t.i32(),
  stageIndex: __t.u32(),
  progressPercent: __t.u32(),
  recordJson: __t.string(),
  createdAt: __t.string(),
  updatedAt: __t.string(),
});
export type Investigations = __Infer<typeof Investigations>;

export const ModuleOwner = __t.object("ModuleOwner", {
  ownerIdentity: __t.identity(),
});
export type ModuleOwner = __Infer<typeof ModuleOwner>;

export const ProviderConfig = __t.object("ProviderConfig", {
  key: __t.string(),
  value: __t.string(),
});
export type ProviderConfig = __Infer<typeof ProviderConfig>;

export const Signals = __t.object("Signals", {
  id: __t.string(),
  investigationId: __t.string(),
  recordJson: __t.string(),
});
export type Signals = __Infer<typeof Signals>;

export const SourceDocuments = __t.object("SourceDocuments", {
  id: __t.string(),
  investigationId: __t.string(),
  recordJson: __t.string(),
});
export type SourceDocuments = __Infer<typeof SourceDocuments>;

export const VoiceSessions = __t.object("VoiceSessions", {
  id: __t.string(),
  investigationId: __t.string(),
  owner: __t.identity(),
  provider: __t.string(),
  status: __t.string(),
  startedAt: __t.string(),
  endedAt: __t.string(),
});
export type VoiceSessions = __Infer<typeof VoiceSessions>;
